name: Learn checkout
on: [workflow_dispatch,push]
jobs:
    get_code:
        runs-on: ubuntu-latest
        steps:
            - name: download the code
              uses: actions/checkout@v4
            - name: maven clean and install
              run: mvn clean 
            - name: maven test
              run: mvn test
            - name: maven package
              run: mvn package
            - name: adding atrifatcs
              uses: actions/upload-artifacts@v3
              with: 
                name: build file
                path: target

