name: Learn checkout
on: [workflow_dispatch,push]
jobs:
    get_code:
        runs-on: ubuntu-latest
        steps:
            - name: download the code
              uses: actions/checkout@v4
            - name: maven clean and install
              run: mvn clean 
            - name: maven test
              run: mvn test
            - name: maven package
              run: mvn package
            - name: adding atrifatcs
              uses: actions/upload-artifact@v4
              with: 
                name: build file
                path: target/springbootjunit5.war
    deploy_from_another_machine:
        runs-on: ubuntu-latest
        needs: get_code
        steps:
            - name: download bulid file
              uses: actions/download-artifact@v4
              with:
                name: build file
