name: Learn checkout
on: [workflow_dispatch,push]
jobs:
    get_code:
        runs-on: ubuntu-latest
        steps:
            - name: download the code
              uses: actions/checkout@v4
            - name: maven package
              run: mvn package
            - name: adding atrifatcs
              uses: actions/upload-artifact@v4
              with: 
                name: build file
                path: target/springbootjunit5.war
            - name: if failed
              if: always()
              run: echo "something went worng...."
    deploy_from_another_machine:
        runs-on: ubuntu-latest
        needs: get_code
        steps:
            - name: download bulid file
              uses: actions/download-artifact@v4
              with:
                name: build file
            - name: print what in it
              run: ls -la
